# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

volumes:
  redis_data:
