version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - '8003:8003'
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=bitnet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '6379:6379'

volumes:
  pgdata:
